Detect and use the fastest download mirror - fixes also #565
Note that we still have to force cURL (re)install if not available or not working properly - but only on initial install.

diff --git a/aegir/tools/bin/barracuda b/aegir/tools/bin/barracuda
--- a/aegir/tools/bin/barracuda
+++ b/aegir/tools/bin/barracuda
@@ -20,7 +20,6 @@ pthBld="/opt/tmp/boa"
 pthIncB="lib/settings/${filIncB}"
 pthIncO="lib/settings/${filIncO}"
 rgUrl="https://raw.githubusercontent.com/omega8cc/boa"
-urlHmr="http://files.aegir.cc/versions/master/aegir"
 vBs="/var/backups"
 
 _TODAY=$(date +%y%m%d 2>&1)
@@ -679,6 +678,41 @@ set_pin_priority() {
   fi
 }
 
+find_mirror() {
+  isNetc=$(which netcat 2>&1)
+  if [ ! -x "${isNetc}" ] || [ -z "${isNetc}" ] ; then
+    apt-get update -qq &> /dev/null
+    apt-get install netcat -y --force-yes --reinstall &> /dev/null
+    sleep 3
+  fi
+  ffMirr=$(which ffmirror 2>&1)
+  if [ -x "${ffMirr}" ] ; then
+    ffList="/var/backups/boa-mirrors.txt"
+    mkdir -p /var/backups
+    echo "jp.files.aegir.cc"  > ${ffList}
+    echo "nl.files.aegir.cc" >> ${ffList}
+    echo "uk.files.aegir.cc" >> ${ffList}
+    echo "us.files.aegir.cc" >> ${ffList}
+    if [ -e "${ffList}" ] ; then
+      _CHECK_MIRROR=$(bash ${ffMirr} < ${ffList} 2>&1)
+      sleep 3
+      _CHECK_MIRROR=$(bash ${ffMirr} < ${ffList} 2>&1)
+      sleep 3
+      _CHECK_MIRROR=$(bash ${ffMirr} < ${ffList} 2>&1)
+      _USE_MIRROR="${_CHECK_MIRROR}"
+    else
+      _USE_MIRROR="files.aegir.cc"
+    fi
+  else
+    _USE_MIRROR="files.aegir.cc"
+  fi
+  if ! netcat -w 5 -z ${_USE_MIRROR} 80 ; then
+    echo "INFO: The mirror ${_USE_MIRROR} doesn't respond, let's try default"
+    _USE_MIRROR="files.aegir.cc"
+  fi
+  urlHmr="http://${_USE_MIRROR}/versions/master/aegir"
+}
+
 check_dns_curl() {
   if [ ! -e "/etc/resolv.conf" ] ; then
     if [ -e "${vBs}/resolv.conf.vanilla" ] ; then
@@ -697,14 +731,21 @@ check_dns_curl() {
     sleep 1
     service pdnsd start &> /dev/null
   fi
-  _CURL_TEST=$(curl -L --max-redirs 10 -k -s --retry 3 --retry-delay 10 -I \
-    "http://files.aegir.cc" 2> /dev/null)
-  if [[ "$_CURL_TEST" =~ "200 OK" ]] ; then
-    _DO_NOTHING=YES
-  else
-    apt-get clean -qq &> /dev/null
-    apt-get update -qq &> /dev/null
-    apt-get install curl -y --force-yes --reinstall &> /dev/null
+  find_mirror
+  isCurl=$(curl --version 2>&1)
+  if [[ ! "$isCurl" =~ "OpenSSL" ]] || [ -z "${isCurl}" ] ; then
+    echo "ERROR: Required cURL package is not available"
+    echo "ERROR: Please install it manually with 'apt-get install curl'"
+    clean_pid_exit
+  fi
+  _CURL_TEST=$(curl -L -k -s \
+    --max-redirs 10 \
+    --retry 3 \
+    --retry-delay 10 \
+    -I "http://${_USE_MIRROR}" 2> /dev/null)
+  if [[ ! "${_CURL_TEST}" =~ "200 OK" ]] ; then
+    echo "ERROR: ${_USE_MIRROR} is not available, please try later"
+    clean_pid_exit
   fi
 }
 
