Add check_root where required.

diff --git a/aegir/tools/bin/boa b/aegir/tools/bin/boa
--- a/aegir/tools/bin/boa
+++ b/aegir/tools/bin/boa
@@ -190,6 +190,17 @@ set_pin_priority ()
   fi
 }
 
+check_root ()
+{
+  if [ `whoami` = "root" ] ; then
+    true
+  else
+    echo "ERROR: This script should be ran as a root user - please `sudo -i` first"
+    exit 1
+  fi
+}
+
+check_root
 check_date
 set_pin_priority
 
diff --git a/aegir/tools/bin/syncpass b/aegir/tools/bin/syncpass
--- a/aegir/tools/bin/syncpass
+++ b/aegir/tools/bin/syncpass
@@ -64,6 +64,18 @@ do_syncpass () {
   fi
 }
 
+check_root ()
+{
+  if [ `whoami` = "root" ] ; then
+    true
+  else
+    echo "ERROR: This script should be ran as a root user - please `sudo -i` first"
+    exit 1
+  fi
+}
+
+check_root
+
 case "$1" in
   fix) uname="$2"
        do_syncpass
