Add "boa info" helper command

diff --git a/aegir/tools/bin/boa b/aegir/tools/bin/boa
--- a/aegir/tools/bin/boa
+++ b/aegir/tools/bin/boa
@@ -1117,7 +1117,64 @@ check_root() {
   fi
 }
 
+display_info() {
+  if [ `whoami` = "root" ]; then
+    _AWS_TEST_A=$(grep cloudimg /etc/fstab 2>&1)
+    _AWS_TEST_B=$(grep cloudconfig /etc/fstab 2>&1)
+    _ETH_TEST=$(ifconfig 2>&1)
+    _VM_TEST=$(uname -a 2>&1)
+    if [[ "${_ETH_TEST}" =~ "venet0" ]]; then
+      _VMFAMILY="VZ"
+    elif [ -e "/proc/bean_counters" ]; then
+      _VMFAMILY="VZ"
+    else
+      _VMFAMILY="XEN"
+    fi
+    if [[ "${_VM_TEST}" =~ "3.7.4-beng" ]] \
+      || [[ "${_VM_TEST}" =~ "3.2.16-beng" ]] \
+      || [[ "${_VM_TEST}" =~ "3.6.15-beng" ]]; then
+      _VMFAMILY="VS"
+    fi
+    if [[ "${_AWS_TEST_A}" =~ "cloudimg" ]] \
+      || [[ "${_AWS_TEST_B}" =~ "cloudconfig" ]]; then
+      _VMFAMILY="AWS"
+    fi
+    _CPU_INFO=$(grep -c processor /proc/cpuinfo 2>&1)
+    _CPU_INFO=${_CPU_INFO//[^0-9]/}
+    _NPROC_TEST=$(which nproc 2>&1)
+    if [ -z "${_NPROC_TEST}" ]; then
+      _CPU_NR="${_CPU_INFO}"
+    else
+      _CPU_NR=$(nproc 2>&1)
+    fi
+    _CPU_NR=${_CPU_NR//[^0-9]/}
+    if [ ! -z "${_CPU_NR}" ] && [ ! -z "${_CPU_INFO}" ] \
+      && [ "${_CPU_NR}" -gt "${_CPU_INFO}" ] && [ "${_CPU_INFO}" -gt "0" ]; then
+      _CPU_NR="${_CPU_INFO}"
+    fi
+    _RAM=$(free -mto | grep Mem: | awk '{ print $2 }' 2>&1)
+    echo
+    thiSys="$(lsb_release -si 2>&1)/$(lsb_release -sc 2>&1) $(uname -m 2>&1)"
+    echo "Aegir on ${thiSys}"
+    echo "  VPS ${_VMFAMILY}"
+    echo "  CPU ${_CPU_NR}"
+    echo "  RAM ${_RAM}"
+    echo
+    echo "Please provide this information,"
+    echo "along with your hosting company name"
+    echo "in the BOA issue queue on GitHub."
+    echo
+    exit 0
+  else
+    echo "ERROR: This script should be ran as a root user"
+    exit 1
+  fi
+}
+
 case "$1" in
+  info)      cmmand="$1"
+             display_info
+  ;;
   in-head)   cmmand="$1"
              kind="$2"
              fqdn="$3"
