Debian Stretch plus PHP 7.2 and 7.1 support

diff --git a/aegir/tools/bin/cluster b/aegir/tools/bin/cluster
--- a/aegir/tools/bin/cluster
+++ b/aegir/tools/bin/cluster
@@ -6,7 +6,7 @@ PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
 _CSF_VRN="12.08"
 _PROXYSQL_VRN="1.3.5-debian8_amd64"
 _UTIL_VRN="0.30.216-pre3126"
-_VNSTAT_VRN="1.15"
+_VNSTAT_VRN="2.0"
 
 _NOISE="-q"
 _INST="/usr/bin/apt-get -y --force-yes ${_NOISE} install"
@@ -45,10 +45,14 @@ check_root() {
     forCer="-fuy --force-yes --reinstall"
     _LSB_TEST=$(which lsb_release 2> /dev/null)
     if [ ! -x "${_LSB_TEST}" ]; then
-      if [ -x "/lib/systemd/systemd" ]; then
-        _OSR=jessie
-      else
-        _OSR=wheezy
+      apt-get clean ${_NOISE}
+      apt-get update ${_NOISE}
+      apt-get install lsb-release ${forCer} ${_NOISE}
+      _OSV=$(lsb_release -si 2>&1)
+      _OSR=$(lsb_release -sc 2>&1)
+      if [ "${_OSV}" != "Debian" ]; then
+        echo "ERROR: Not supported OS detected: ${_OSV}/${_OSR}"
+        exit 1
       fi
       echo
       echo "## MAIN REPOSITORIES"                                                       > /etc/apt/sources.list
@@ -79,9 +83,9 @@ check_root() {
     if [ "${_OSR}" = "jessie" ]; then
       _BENG_SERIES="4.1"
       _BNG_VERSION="4.1.50-vs2.3.8.6"
-    elif [ "${_OSR}" = "wheezy" ]; then
-      _BENG_SERIES="3.18"
-      _BNG_VERSION="3.18.44-vs2.3.7.5"
+    elif [ "${_OSR}" = "stretch" ]; then
+      _BENG_SERIES="4.1"
+      _BNG_VERSION="4.1.50-vs2.3.8.6"
     else
       echo "ERROR: Not supported OS detected: ${_OSV}/${_OSR}"
       exit 1
