Move around backups backend tools

diff --git a/aegir/tools/bin/multiback b/aegir/tools/bin/multiback
--- a/aegir/tools/bin/multiback
+++ b/aegir/tools/bin/multiback
@@ -175,7 +175,21 @@ _validate_credentials() {
 _load_credentials() {
   local _service="$1"
   local _user="$2"
-  local _cred_file="/data/disk/${_user}/static/control/remote_backups/credentials/${_service}.txt"
+  if [ "${_user}" != "arch" ] && [ "${_user}" != "global_user" ]; then
+    local _cred_file="/data/disk/${_user}/static/control/remote_backups/credentials/${_service}.txt"
+    local _secret_file="/data/disk/${_user}/remote_backups/.secret.txt"
+  fi
+  if [ "${_user}" = "global_user" ]; then
+    local _cred_file="/root/.remote_backups/credentials/${_service}.txt"
+    local _secret_file="/root/.remote_backups/.secret.txt"
+  fi
+
+  if [ -f "${_secret_file}" ]; then
+    export PASSPHRASE=$(cat "${_secret_file}")
+  else
+    echo "Secret file ${_secret_file} not found. Unable to proceed."
+    exit 1
+  fi
 
   if [ ! -f "${_cred_file}" ]; then
     echo "Error: Credentials file '${_cred_file}' not found."
@@ -260,14 +274,23 @@ _validate_paths() {
 # Function to load paths configuration
 _load_paths() {
   local _user="$1"
-  local _paths_file="/data/disk/${_user}/remote_backups/paths.txt"
+
+  local _paths_file="/data/disk/${_user}/remote_backups/paths/paths.txt"
+
+  if [ "${_user}" = "global_user" ]; then
+    local _paths_file="/data/disk/${_user}/remote_backups/paths/paths.txt"
+    local _cred_file="/root/.remote_backups/credentials/${_service}.txt"
+    local _secret_file="/root/.remote_backups/.secret.txt"
+  fi
 
   if [ ! -f "${_paths_file}" ]; then
     echo "Error: Paths configuration file '${_paths_file}' not found."
     exit 1
   fi
 
-  _validate_paths "${_paths_file}" "${_user}"
+  if [ "${_user}" != "arch" ] && [ "${_user}" != "global_user" ]; then
+    _validate_paths "${_paths_file}" "${_user}"
+  fi
 
   if [ "${#_PATHS_ARRAY[@]}" -eq 0 ]; then
     echo "Error: No valid paths found in '${_paths_file}'. Check ${_LOG_FILE} for details."
