Improve apt/sources updates

diff --git a/aegir/tools/bin/mycnfup b/aegir/tools/bin/mycnfup
--- a/aegir/tools/bin/mycnfup
+++ b/aegir/tools/bin/mycnfup
@@ -19,6 +19,8 @@ _PHP_FPM_WORKERS=AUTO
 _CUSTOM_CONFIG_SQL=NO
 _RESERVED_RAM=0
 
+_APT_XTR="-y --force-yes"
+_INST="/usr/bin/apt-get --allow-unauthenticated ${_APT_XTR} install"
 crlGet="-L --max-redirs 10 -k -s --retry 10 --retry-delay 5 -A iCab"
 forCer="-fuy --allow-unauthenticated --reinstall"
 vBs="/var/backups"
@@ -65,6 +67,48 @@ check_root() {
     if [[ "${_AWS_TEST_A}" =~ "amazon" ]] \
       || [[ "${_AWS_TEST_B}" =~ "ec2" ]]; then
       _VMFAMILY="AWS"
+    fi
+
+    _LSB_TEST=$(which lsb_release 2> /dev/null)
+    if [ ! -x "${_LSB_TEST}" ]; then
+      apt-get clean ${_APT_XTR}
+      rm -f -r /var/lib/apt/lists/*
+      apt-get update ${_APT_XTR}
+      apt-get install lsb-release ${forCer} ${_APT_XTR}
+      _OSV=$(lsb_release -si 2>&1)
+      _OSR=$(lsb_release -sc 2>&1)
+      if [ "${_OSV}" != "Debian" ]; then
+        echo "ERROR: Not supported OS detected: ${_OSV}/${_OSR}"
+        exit 1
+      fi
+      echo
+      echo "## MAIN REPOSITORIES"                                                       > /etc/apt/sources.list
+      echo "deb http://http.debian.net/debian/ ${_OSR} main contrib non-free"          >> /etc/apt/sources.list
+      echo "deb-src http://http.debian.net/debian/ ${_OSR} main contrib non-free"      >> /etc/apt/sources.list
+      echo ""                                                                          >> /etc/apt/sources.list
+      if [ "${_OSR}" = "stretch" ]; then
+        echo "## MAJOR BUG FIX UPDATES produced after the final release"               >> /etc/apt/sources.list
+        echo "deb http://http.debian.net/debian/ ${_OSR}-updates main"                 >> /etc/apt/sources.list
+        echo "deb-src http://http.debian.net/debian/ ${_OSR}-updates main"             >> /etc/apt/sources.list
+        echo ""                                                                        >> /etc/apt/sources.list
+        echo "## DEBIAN PROPOSED UPDATES"                                              >> /etc/apt/sources.list
+        echo "deb http://http.debian.net/debian/ ${_OSR}-proposed-updates main"        >> /etc/apt/sources.list
+        echo ""                                                                        >> /etc/apt/sources.list
+      fi
+      echo "## DEBIAN SECURITY UPDATES"                                                >> /etc/apt/sources.list
+      echo "deb http://security.debian.org/ ${_OSR}/updates main contrib non-free"     >> /etc/apt/sources.list
+      echo "deb-src http://security.debian.org/ ${_OSR}/updates main contrib non-free" >> /etc/apt/sources.list
+      echo
+      apt-get clean ${_APT_XTR}
+      rm -f -r /var/lib/apt/lists/*
+      apt-get update ${_APT_XTR}
+      apt-get install lsb-release ${forCer} ${_APT_XTR}
+    fi
+    _OSV=$(lsb_release -si 2>&1)
+    _OSR=$(lsb_release -sc 2>&1)
+    if [ "${_OSV}" != "Debian" ]; then
+      echo "ERROR: Not supported OS detected: ${_OSV}/${_OSR}"
+      exit 1
     fi
 
     if [ "${_VMFAMILY}" = "VS" ]; then
