Use latest GoAccess

diff --git a/aegir/tools/bin/weblogx b/aegir/tools/bin/weblogx
--- a/aegir/tools/bin/weblogx
+++ b/aegir/tools/bin/weblogx
@@ -3,6 +3,9 @@
 PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
 SHELL=/bin/bash
 
+crlGet="-L --max-redirs 10 -k -s --retry 10 --retry-delay 5 -A iCab"
+_GOACCESS_VRN=1.3
+
 check_root() {
   if [ `whoami` = "root" ]; then
     ionice -c2 -n7 -p $$
@@ -31,25 +34,90 @@ check_root() {
 }
 check_root
 
-if_install() {
-	forCer="-fuy --allow-unauthenticated --reinstall"
-	isGoacs=$(which goaccess 2>&1)
-	if [ ! -x "${isGoacs}" ] || [ -z "${isGoacs}" ]; then
-	  apt-get update -qq &> /dev/null
-	  apt-get install goaccess ${forCer} &> /dev/null
-	  sleep 3
-	  if [ -e "/etc/goaccess.conf" ]; then
-	    echo 'date-format %d/%b/%Y' >> /etc/goaccess.conf
-	    echo 'time-format %H:%M:%S' >> /etc/goaccess.conf
-	    ### echo 'log-format "%^" %h [%d:%t %^] "%r" %s %b %^ %^ "%R" "%u" %T "%^"' >> /etc/goaccess.conf
-	    echo 'log-format "%^" %v [%d:%t %^] "%r" %s %b %r_length %b "%R" "%u" %T "%^"' >> /etc/goaccess.conf
-	    sleep 3
+find_fast_mirror() {
+  isNetc=$(which netcat 2>&1)
+  if [ ! -x "${isNetc}" ] || [ -z "${isNetc}" ]; then
+    rm -f /etc/apt/sources.list.d/openssl.list
+    apt-get update -qq &> /dev/null
+    apt-get install netcat ${forCer} &> /dev/null
+    sleep 3
+  fi
+  ffMirr=$(which ffmirror 2>&1)
+  if [ -x "${ffMirr}" ]; then
+    ffList="/var/backups/boa-mirrors.txt"
+    mkdir -p /var/backups
+    if [ ! -e "${ffList}" ]; then
+      echo "jp.files.aegir.cc"  > ${ffList}
+      echo "nl.files.aegir.cc" >> ${ffList}
+      echo "uk.files.aegir.cc" >> ${ffList}
+      echo "us.files.aegir.cc" >> ${ffList}
+    fi
+    if [ -e "${ffList}" ]; then
+      _CHECK_MIRROR=$(bash ${ffMirr} < ${ffList} 2>&1)
+      _USE_MIR="${_CHECK_MIRROR}"
+      [[ "${_USE_MIR}" =~ "printf" ]] && _USE_MIR="files.aegir.cc"
     else
-      echo "ERROR: goaccess was not found.."
-      exit 1
+      _USE_MIR="files.aegir.cc"
     fi
   else
-    echo "GREAT: goaccess was found!"
+    _USE_MIR="files.aegir.cc"
+  fi
+  if ! netcat -w 10 -z "${_USE_MIR}" 80; then
+    echo "INFO: The mirror ${_USE_MIR} doesn't respond, let's try default"
+    _USE_MIR="104.245.208.226"
+  fi
+  urlDev="http://${_USE_MIR}/dev"
+  urlHmr="http://${_USE_MIR}/versions/master/aegir"
+}
+
+install_goaccess() {
+  echo "Installing GoAccess ${_GOACCESS_VRN} with dependencies..."
+  cd
+  apt-get clean -qq
+  rm -f -r /var/lib/apt/lists/*
+  apt-get update -qq
+  aptitude purge goaccess -y -qq
+  apt-get install libncurses5-dev -y
+  apt-get install libncursesw5-dev -y
+  find_fast_mirror
+  mkdir -p /opt/tmp
+  cd /opt/tmp
+  rm -rf /opt/tmp/goaccess
+  curl ${crlGet} "${urlDev}/src/goaccess-${_GOACCESS_VRN}.tar.gz" | tar -xzf -
+  cd /var/opt/goaccess-${_GOACCESS_VRN}
+  bash ./configure --prefix=/usr --enable-utf8 --enable-geoip=legacy
+  make --quiet
+  make --quiet install
+  cd
+}
+
+if_install() {
+  isGoacs=$(which goaccess 2>&1)
+  if [ ! -x "${isGoacs}" ] \
+    || [ -z "${isGoacs}" ]; then
+    install_goaccess
+  else
+    _GOACCESS_ITD=$(goaccess --version 2>&1 \
+      | tr -d "\n" \
+      | tr -d "v=" \
+      | tr -d "For" \
+      | cut -d" " -f3 \
+      | awk '{ print $1}' 2>&1)
+    if [ "${_GOACCESS_ITD}" = "${_GOACCESS_VRN}." ]; then
+      echo "Latest GoAccess ${_GOACCESS_VRN} already installed"
+    else
+      install_goaccess
+    fi
+  fi
+  if [ -e "/usr/etc/goaccess/goaccess.conf" ]; then
+    echo 'date-format %d/%b/%Y' >> /usr/etc/goaccess/goaccess.conf
+    echo 'time-format %H:%M:%S' >> /usr/etc/goaccess/goaccess.conf
+    ### echo 'log-format "%^" %h [%d:%t %^] "%r" %s %b %^ %^ "%R" "%u" %T "%^"' >> /usr/etc/goaccess/goaccess.conf
+    echo 'log-format "%^" %v [%d:%t %^] "%r" %s %b %r_length %b "%R" "%u" %T "%^"' >> /usr/etc/goaccess/goaccess.conf
+    sleep 1
+  else
+    echo "ERROR: GoAccess was not found.."
+    exit 1
   fi
 }
 if_install
