Run most of crontab, install and upgrade tasks with low priority (nice, ionice) - fixes #780

diff --git a/aegir/tools/bin/xboa b/aegir/tools/bin/xboa
--- a/aegir/tools/bin/xboa
+++ b/aegir/tools/bin/xboa
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-SHELL=/bin/bash
 PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/usr/sbin:/bin:/sbin
+SHELL=/bin/bash
 _WEBG=www-data
 
 ###
@@ -983,6 +983,7 @@ ssl_gen() {
 
 check_root() {
   if [ `whoami` = "root" ]; then
+    ionice -c2 -n7 -p$$
     chmod a+w /dev/null
     if [ ! -e "/dev/fd" ]; then
       if [ -e "/proc/self/fd" ]; then
@@ -996,7 +997,17 @@ check_root() {
       _BCC_EMAIL=${_MY_EMAIL//\\\@/\@}
     fi
   else
-    echo "ERROR: This script should be ran as a root user - please `sudo -i` first"
+    echo "ERROR: This script should be ran as a root user"
+    exit 1
+  fi
+  _DF_TEST=$(df -kTh / -l \
+    | grep '/' \
+    | sed 's/\%//g' \
+    | awk '{print $6}' 2> /dev/null)
+  _DF_TEST=${_DF_TEST//[^0-9]/}
+  if [ ! -z "${_DF_TEST}" ] && [ "${_DF_TEST}" -gt "90" ]; then
+    echo "ERROR: Your disk space is almost full !!! ${_DF_TEST}/100"
+    echo "ERROR: We can not proceed until it is below 90/100"
     exit 1
   fi
 }
