Pid update

diff --git a/aegir/tools/bin/xboa b/aegir/tools/bin/xboa
--- a/aegir/tools/bin/xboa
+++ b/aegir/tools/bin/xboa
@@ -451,39 +451,50 @@ migrate_prepare() {
     && [ ! -z "${_HDB}" ] \
     && [ ! -e "${_USR}/src/prev_hostmaster.sql" ] \
     && [ ! -e "${_USR}/log/exported.pid" ]; then
-    mysqldump \
-      --single-transaction \
-      --quick \
-      --no-autocommit \
-      --default-character-set=utf8 \
-      --hex-blob ${_HDB} \
-      comments \
-      history \
-      hosting_cron \
-      hosting_client \
-      hosting_client_user \
-      hosting_context \
-      hosting_package \
-      hosting_package_instance \
-      hosting_package_languages \
-      hosting_platform \
-      hosting_platform_client_access \
-      hosting_site \
-      hosting_site_alias \
-      hosting_site_backups \
-      hosting_task \
-      hosting_task_arguments \
-      hosting_task_log \
-      node \
-      node_access \
-      node_comment_statistics \
-      node_counter \
-      node_revisions \
-      url_alias \
-      userprotect \
-      users \
-      users_roles \
-      > ${_USR}/src/prev_hostmaster.sql
+      mysqldump \
+        --single-transaction \
+        --quick \
+        --no-autocommit \
+        --default-character-set=utf8 \
+        --hex-blob ${_HDB} \
+        field_data_body \
+        field_data_comment_body \
+        field_revision_body \
+        field_revision_comment_body \
+        filter \
+        filter_format \
+        history \
+        hosting_backup_gc_sites \
+        hosting_client \
+        hosting_client_user \
+        hosting_context \
+        hosting_cron \
+        hosting_package \
+        hosting_package_instance \
+        hosting_package_languages \
+        hosting_platform \
+        hosting_platform_client_access \
+        hosting_site \
+        hosting_site_alias \
+        hosting_site_backups \
+        hosting_ssl_cert \
+        hosting_ssl_cert_ips \
+        hosting_ssl_site \
+        hosting_task \
+        hosting_task_arguments \
+        hosting_task_log \
+        node \
+        node_access \
+        node_comment_statistics \
+        node_revision \
+        node_type \
+        role \
+        role_permission \
+        url_alias \
+        userprotect \
+        users \
+        users_roles \
+        > ${_USR}/src/prev_hostmaster.sql
     run_drush8_hmr_cmd "@hostmaster vset --always-set maintenance_mode 1"
     if [ -e "${_USR}/src/prev_hostmaster.sql" ]; then
       echo "INFO: hostmaster ${oct} db export complete"
@@ -605,6 +616,7 @@ migrate_prepare() {
       && [ ! -z "${_CLIENT_SUBSCR}" ] \
       && [ ! -z "${_CLIENT_CORES}" ]; then
       ssh root@${tgt} "/opt/local/bin/boa in-octopus ${_CLIENT_EMAIL} ${_TGT_HM_USER} none ${_CLIENT_OPTION} ${_CLIENT_SUBSCR} ${_CLIENT_CORES}"
+      ssh root@${tgt} "/bin/rm -f /data/disk/${_TGT_HM_USER}/tools/le/.ctrl/ssl-demo-mode.pid"
       echo "INFO: new octopus ${_TGT_HM_USER} setup on ${tgt} complete"
     else
       echo "ALRT: new octopus ${_TGT_HM_USER} setup on ${tgt} failed because of missing arguments"
@@ -621,6 +633,15 @@ migrate_prepare() {
 }
 
 migrate_init() {
+  _USR=/data/disk/${oct}
+  if [ ! -e "${_USR}/tools/le/letsencrypt.sh" ]; then
+    echo
+    echo "ERROR: This version of xboa migration tool supports only BOA-3.1.0 or newer"
+    echo "ERROR: Please upgrade ${oct} instance to current BOA stable before trying again"
+    echo "Bye."
+    echo
+    exit 1
+  fi
   rm -f /root/scentral_migration_notice.sh.txt
   if [ "${oct}" = "xusage" ]; then
     echo "INFO: ${cmd} for ${oct} to ${tgt} start"
@@ -773,6 +794,11 @@ migrate_init() {
             --ignore-errors \
             -e ssh ${_USR}/config/server_master/nginx/platform.d/* \
             root@${tgt}:${_DST}/config/server_master/nginx/platform.d/ &> /dev/null
+
+          rsync -aAXqu \
+            --ignore-errors \
+            -e ssh ${_USR}/tools/le \
+            root@${tgt}:${_DST}/tools/ &> /dev/null
 
           echo "INFO: ${cmd} for ${oct} to ${tgt} ${dst} complete"
           touch ${_USR}/log/transferred.pid
