PHP: Conversion to multi-version setup (step 5)

diff --git a/aegir/conf/php53-fpm b/aegir/conf/php53-fpm
--- a/aegir/conf/php53-fpm
+++ b/aegir/conf/php53-fpm
@@ -1,4 +1,4 @@
-#!/bin/sh
+#! /bin/sh
 
 ### BEGIN INIT INFO
 # Provides:          php53-fpm
@@ -15,120 +15,134 @@ exec_prefix=${prefix}
 php_fpm_BIN=/opt/php53/sbin/php-fpm
 php_fpm_CONF=/opt/php53/etc/php53-fpm.conf
 php_fpm_PID=/var/run/php53-fpm.pid
-php_opts="--fpm-config $php_fpm_CONF -c /opt/php53/etc/php53.ini"
+php_opts="--fpm-config $php_fpm_CONF --pid $php_fpm_PID -c /opt/php53/etc/php53.ini"
 
 wait_for_pid () {
-  try=0
+	try=0
 
-  while test $try -lt 8 ; do
+	while test $try -lt 5 ; do
 
-    case "$1" in
-      'created')
-      if [ -f "$2" ] ; then
-        try=''
-        break
-      fi
-      ;;
+		case "$1" in
+			'created')
+			if [ -f "$2" ] ; then
+				try=''
+				break
+			fi
+			;;
 
-      'removed')
-      if [ ! -f "$2" ] ; then
-        try=''
-        break
-      fi
-      ;;
-    esac
+			'removed')
+			if [ ! -f "$2" ] ; then
+				try=''
+				break
+			fi
+			;;
+		esac
 
-    echo -n .
-    try=`expr $try + 1`
-    sleep 1
+		echo -n .
+		try=`expr $try + 1`
+		sleep 1
 
-  done
+	done
 
 }
 
 case "$1" in
-  start)
-    echo -n "Starting php53-fpm.."
+	start)
+		echo -n "Starting php53-fpm.."
 
-    $php_fpm_BIN $php_opts
+		$php_fpm_BIN --daemonize $php_opts
 
-    if [ -z "$?" ] ; then
-      echo " continue.."
-      exit 1
-    fi
+		if [ "$?" != 0 ] ; then
+			echo " failed"
+			exit 1
+		fi
 
-    wait_for_pid created $php_fpm_PID
+		wait_for_pid created $php_fpm_PID
 
-    if [ -n "$try" ] ; then
-      echo " failed try $try"
-      exit 1
-    else
-      echo " done"
-    fi
-  ;;
+		if [ -n "$try" ] ; then
+			echo " failed"
+			exit 1
+		else
+			echo " done"
+		fi
+	;;
 
-  stop)
-    echo -n "Gracefully shutting down php53-fpm.."
+	stop)
+		echo -n "Gracefully shutting down php53-fpm.."
 
-    if [ ! -r $php_fpm_PID ] ; then
-      echo "warning, no pid file found - php53-fpm not running ?"
-      exit 1
-    fi
+		if [ ! -r $php_fpm_PID ] ; then
+			echo "warning, no pid file found - php53-fpm is not running ?"
+			exit 1
+		fi
 
-    kill -QUIT `cat $php_fpm_PID`
+		kill -QUIT `cat $php_fpm_PID`
 
-    wait_for_pid removed $php_fpm_PID
+		wait_for_pid removed $php_fpm_PID
 
-    if [ -n "$try" ] ; then
-      echo " failed. Use force-quit"
-      exit 1
-    else
-      echo " done"
-    fi
-  ;;
+		if [ -n "$try" ] ; then
+			echo " failed. Use force-quit"
+			exit 1
+		else
+			echo " done"
+		fi
+	;;
 
-  force-quit)
-    echo -n "Terminating php53-fpm.."
+	status)
+		if [ ! -r $php_fpm_PID ] ; then
+			echo "php53-fpm is stopped"
+			exit 0
+		fi
 
-    if [ ! -r $php_fpm_PID ] ; then
-      echo "warning, no pid file found - php53-fpm not running ?"
-      exit 1
-    fi
+		PID=`cat $php_fpm_PID`
+		if ps -p $PID | grep -q $PID; then
+			echo "php53-fpm (pid $PID) is running..."
+		else
+			echo "php53-fpm dead but pid file exists"
+		fi
+	;;
 
-    kill -TERM `cat $php_fpm_PID`
+	force-quit)
+		echo -n "Terminating php53-fpm.."
 
-    wait_for_pid removed $php_fpm_PID
+		if [ ! -r $php_fpm_PID ] ; then
+			echo "warning, no pid file found - php53-fpm is not running ?"
+			exit 1
+		fi
 
-    if [ -n "$try" ] ; then
-      echo " failed"
-      exit 1
-    else
-      echo " done"
-    fi
-  ;;
+		kill -TERM `cat $php_fpm_PID`
 
-  restart)
-    $0 stop
-    $0 start
-  ;;
+		wait_for_pid removed $php_fpm_PID
 
-  reload)
+		if [ -n "$try" ] ; then
+			echo " failed"
+			exit 1
+		else
+			echo " done"
+		fi
+	;;
 
-    echo -n "Reload service php53-fpm.."
+	restart)
+		$0 stop
+		$0 start
+	;;
 
-    if [ ! -r $php_fpm_PID ] ; then
-      echo "warning, no pid file found - php53-fpm not running ?"
-      exit 1
-    fi
+	reload)
 
-    kill -USR2 `cat $php_fpm_PID`
+		echo -n "Reloading service php53-fpm.."
 
-    echo " done"
-  ;;
+		if [ ! -r $php_fpm_PID ] ; then
+			echo "warning, no pid file found - php53-fpm is not running ?"
+			exit 1
+		fi
 
-  *)
-    echo "Usage: $0 {start|stop|force-quit|restart|reload}"
-    exit 1
-  ;;
+		kill -USR2 `cat $php_fpm_PID`
+
+		echo " done"
+	;;
+
+	*)
+		echo "Usage: $0 {start|stop|force-quit|restart|reload|status}"
+		exit 1
+	;;
 
 esac
